#44 Fix Added moveto message for digression warning
pyslackers/sirbot-pythondev pull request #48
Opened 2017-07-08 14:38 UTC by ngrjs

Partial fix for digression warning. Working as a message, need to convert it to slash command.

2017-07-16 08:32 UTC, ovv commented
Working great @ngrjs 

I can merge or do you want to wait to convert it to a slash command ?

2017-07-16 18:46 UTC, ngrjs commented
I wanted to convert that into slash command. But, I haven't been able to make slash commands working at my end.

2017-07-16 19:56 UTC, ovv commented
Oh yeah forgot about that bit. 

Could you open an issue in pyslackers/sirbot-slack with your configuration file, what you do with ngrok and the log of sirbot ?

Thanks

2017-07-17 04:07 UTC, ngrjs commented
Yup 👍

2017-07-18 18:41 UTC, ovv requested changes
:+1: Nice work

Just some small tweaks and one ting to change but I need to test to remember exactly how it works. The idea being that we don't want everyone to see the errors message `Sorry I can not understand the destination.`. There is a way to display them only to the person triggering the command. I'll let you know how to do it.

2017-07-18 18:41 UTC, ovv commented on sirbot.yml
> +        Looks like conversation is going off topic. Please move the conversation to {}
Not the same text as in `test.yml`. I guess the correct formatting is the other one

2017-07-18 18:41 UTC, ovv commented on sirbot/pythondev/slack.py
> +        print("here")
You should delete that

2017-07-18 18:41 UTC, ovv commented on sirbot/pythondev/slack.py
> +        if to_id.startswith('#'):
`elif`

2017-07-18 18:41 UTC, ovv commented on sirbot/pythondev/slack.py
> +            to_id = to_id.replace('#', '')
you might want to add `.strip()` too in case someone put a space.

2017-07-18 18:41 UTC, ovv commented on sirbot/pythondev/slack.py
> +        to_id = command.text
you should rename `to_id` to something more explicit. It's not the `id` but the `name`

2017-07-18 18:41 UTC, ovv commented on test.yml
> +        Looks like conversation is going off topic. Please move the conversation to <#{}|channel>
I believe `channel` should be the actual channel name (`to.name`)

2017-07-18 21:38 UTC, ovv commented
Hey @ngrjs 

I made some update to the slack commands API yesterday to try to makes them easier. By default when using `command.response()` the response will be `in_channel` meaning that everybody will be able to see it. To change that you can pass `ephemeral` as the `type_` argument and the message will be only displayed for the user using the command.

this can be changed later by `reponse.response_type = 'ephemeral'`

Due to the changes the `public` argument to the `add_command` as been deleted.

I updated other commands so you can take a look :)

2017-07-19 16:35 UTC, closed without merging