Updated moveto command to the latest format
pyslackers/sirbot-pythondev pull request #63
Opened 2017-07-19 18:36 UTC by ngrjs

/moveto command is now compatible with the new changes.

2017-07-19 18:52 UTC, ovv requested changes
One small change to improve readability and it's ok :)

You should also fix the travis test that is failing. If you have never use travis and want some help don't hesitate to ask.

2017-07-19 18:52 UTC, ovv commented on pythondev/slack.py
> +        response = command.response()
You can pass the argument `type_='ephemeral` here so you don't need to set it every time and code will be more readable.

2017-07-19 19:19 UTC, ngrjs commented on pythondev/slack.py
> +        response = command.response()
Okay. I will make the changes.

2017-07-20 16:57 UTC, ovv approved these changes

2017-07-20 16:57 UTC, merged